/**
 * dedications.ts — le canzoni dedicate. GENERATO da build-dedications.mjs:
 * ogni brano è risolto al suo brano su Deezer (API pubblica, nessuna chiave),
 * così il player a incorporo (widget.deezer.com) lo suona direttamente.
 *
 * 300 dediche: una canzone e una dedica per OGNI giorno, in
 * rotazione deterministica (vedi dailyIndex in music.ts) — mai un giorno
 * senza. "support" risponde al pulsante delle giornate no.
 *
 * Per rigenerare/ampliare:  node build-dedications.mjs
 */

export interface Dedication {
  title: string;
  artist: string;
  year: number;
  /** the message written for her — the heart of the gift. */
  text: string;
  /** deezer.com/track/<id> url (feeds the official embed player). */
  url: string;
}

export const LOVE_DEDICATIONS: Dedication[] = [
  { title: "Here Comes the Sun", artist: "The Beatles", year: 0, text: "Certe persone portano il sole senza accorgersene. Tu, per esempio.", url: "https://www.deezer.com/track/116348464" },
  { title: "Something", artist: "The Beatles", year: 0, text: "Non so spiegare cosa mi fai. So solo che è la cosa più bella che mi capita.", url: "https://www.deezer.com/track/116348454" },
  { title: "In My Life", artist: "The Beatles", year: 0, text: "Di tutti i posti e le persone della mia vita, tu sei quella che amo di più.", url: "https://www.deezer.com/track/116348272" },
  { title: "Let It Be", artist: "The Beatles", year: 0, text: "Non tutto va aggiustato: certe cose basta tenerle con cura. Me l'hai insegnato tu.", url: "https://www.deezer.com/track/116348656" },
  { title: "Yesterday", artist: "The Beatles", year: 0, text: "C'è un prima e un dopo averti conosciuta. Il dopo mi piace di più.", url: "https://www.deezer.com/track/116348612" },
  { title: "I Will", artist: "The Beatles", year: 0, text: "Ti ho amata prima di conoscerti, e ti amerò anche dopo. Nel mezzo, sono fortunato.", url: "https://www.deezer.com/track/116348222" },
  { title: "And I Love Her", artist: "The Beatles", year: 0, text: "Dammi un motivo qualsiasi: io ti amo comunque, e più di così non si può.", url: "https://www.deezer.com/track/116348434" },
  { title: "Imagine", artist: "John Lennon", year: 0, text: "Un mondo migliore sembra più credibile da quando ci sei tu.", url: "https://www.deezer.com/track/7193834" },
  { title: "Woman", artist: "John Lennon", year: 0, text: "Tutto quello che sono te lo devo un po'. Grazie di esserci.", url: "https://www.deezer.com/track/7163159" },
  { title: "Oh Yoko!", artist: "John Lennon", year: 0, text: "Nel mezzo di qualsiasi cosa, il tuo nome mi salva. Sempre.", url: "https://www.deezer.com/track/7193843" },
  { title: "What a Wonderful World", artist: "Louis Armstrong", year: 0, text: "Con te anche una strada qualunque diventa un posto da guardare meglio.", url: "https://www.deezer.com/track/906625" },
  { title: "La Vie en Rose", artist: "Louis Armstrong", year: 0, text: "Quando ci sei tu, vedo tutto un po' più rosa. Ed è bellissimo.", url: "https://www.deezer.com/track/86542983" },
  { title: "My Girl", artist: "The Temptations", year: 0, text: "Ho la mia primavera anche a gennaio: sei tu.", url: "https://www.deezer.com/track/538643262" },
  { title: "Ain't No Mountain High Enough", artist: "Marvin Gaye", year: 0, text: "Non c'è distanza abbastanza grande da tenermi lontano da te.", url: "https://www.deezer.com/track/646327092" },
  { title: "Let's Stay Together", artist: "Al Green", year: 0, text: "Nei giorni belli e in quelli storti: io resto. È una promessa.", url: "https://www.deezer.com/track/97095572" },
  { title: "Stand by Me", artist: "Ben E. King", year: 0, text: "Finché ci sei tu accanto, non ho paura di niente.", url: "https://www.deezer.com/track/136710424" },
  { title: "Unchained Melody", artist: "The Righteous Brothers", year: 0, text: "Il tempo passa lento quando non ci sei. Torna, che ti aspetto.", url: "https://www.deezer.com/track/885544" },
  { title: "At Last", artist: "Etta James", year: 0, text: "Finalmente. Ti ho cercata in tante canzoni e sei sempre stata tu.", url: "https://www.deezer.com/track/2171224" },
  { title: "I Only Have Eyes for You", artist: "The Flamingos", year: 0, text: "In una stanza piena di gente, vedo solo te. Sempre.", url: "https://www.deezer.com/track/140044655" },
  { title: "Can't Help Falling in Love", artist: "Elvis Presley", year: 0, text: "Certe cose sono inevitabili. Innamorarmi di te è stata la più dolce.", url: "https://www.deezer.com/track/551383" },
  { title: "Love Me Tender", artist: "Elvis Presley", year: 0, text: "Trattami piano e io sarò tuo per sempre. Lo sono già.", url: "https://www.deezer.com/track/7675088" },
  { title: "Your Song", artist: "Elton John", year: 0, text: "Non ho gran che da offrire, solo questa: una vita a dirti quanto sei speciale.", url: "https://www.deezer.com/track/880181" },
  { title: "Tiny Dancer", artist: "Elton John", year: 0, text: "Balla pure la tua vita: io ti tengo la mano tutto il tempo.", url: "https://www.deezer.com/track/1151503" },
  { title: "Wonderful Tonight", artist: "Eric Clapton", year: 0, text: "Non te ne accorgi neanche di quanto sei bella. Io sì, ogni sera.", url: "https://www.deezer.com/track/1175626" },
  { title: "Something in the Way She Moves", artist: "James Taylor", year: 0, text: "Basta un tuo gesto qualunque e mi si sistema la giornata.", url: "https://www.deezer.com/track/6523606" },
  { title: "How Sweet It Is (To Be Loved by You)", artist: "James Taylor", year: 0, text: "Non sapevo cosa mi mancasse finché non sei arrivata tu.", url: "https://www.deezer.com/track/6523617" },
  { title: "The Book of Love", artist: "Peter Gabriel", year: 0, text: "Il libro dell'amore è lungo e noioso, dicono. Con te non ne ho saltato una pagina.", url: "https://www.deezer.com/track/540503712" },
  { title: "In Your Eyes", artist: "Peter Gabriel", year: 0, text: "Negli occhi tuoi trovo la luce quando fuori è buio.", url: "https://www.deezer.com/track/540503512" },
  { title: "Just the Way You Are", artist: "Billy Joel", year: 0, text: "Non cambiare niente per me: ti amo esattamente come sei.", url: "https://www.deezer.com/track/988630" },
  { title: "She's Always a Woman", artist: "Billy Joel", year: 0, text: "Con tutte le tue contraddizioni, resti la cosa più vera che ho.", url: "https://www.deezer.com/track/988632" },
  { title: "Songbird", artist: "Fleetwood Mac", year: 0, text: "A te dedico le parole che non riesco a dire: ti amo, come non ho mai amato prima.", url: "https://www.deezer.com/track/63480991" },
  { title: "Landslide", artist: "Fleetwood Mac", year: 0, text: "Gli anni passano, io cambio, ma la voglia di stare con te no.", url: "https://www.deezer.com/track/3599559" },
  { title: "Have I Told You Lately", artist: "Rod Stewart", year: 0, text: "Te l'ho detto oggi quanto ti amo? Nel caso: tantissimo.", url: "https://www.deezer.com/track/2550674" },
  { title: "Make You Feel My Love", artist: "Adele", year: 0, text: "Non c'è niente che non farei per farti sentire quanto ti amo.", url: "https://www.deezer.com/track/940347" },
  { title: "Lovesong", artist: "Adele", year: 0, text: "Ovunque io sia, quando ci sei tu sono a casa.", url: "https://www.deezer.com/track/8086135" },
  { title: "To Make You Feel My Love", artist: "Bob Dylan", year: 0, text: "Da quando ti conosco so cosa vuol dire volere il bene di qualcuno più del proprio.", url: "https://www.deezer.com/track/1014190" },
  { title: "I Want to Hold Your Hand", artist: "The Beatles", year: 0, text: "Mi basta poco: la tua mano nella mia e il mondo può aspettare.", url: "https://www.deezer.com/track/116348598" },
  { title: "God Only Knows", artist: "The Beach Boys", year: 0, text: "Solo il cielo sa dove sarei senza di te. Meno bene, questo è certo.", url: "https://www.deezer.com/track/3102931" },
  { title: "Wouldn't It Be Nice", artist: "The Beach Boys", year: 0, text: "Immagino i nostri giorni insieme e mi viene da sorridere come uno scemo.", url: "https://www.deezer.com/track/3091978" },
  { title: "Then He Kissed Me", artist: "The Crystals", year: 0, text: "Ricordo ancora com'era il mondo un attimo prima di te. Grigio.", url: "https://www.deezer.com/track/12809347" },
  { title: "This Will Be (An Everlasting Love)", artist: "Natalie Cole", year: 0, text: "Questo, tra noi, non è un capriccio: è per sempre.", url: "https://www.deezer.com/track/3325466" },
  { title: "Never Tear Us Apart", artist: "INXS", year: 0, text: "Che venga qualunque cosa: niente ci separa.", url: "https://www.deezer.com/track/11282935" },
  { title: "Wicked Game", artist: "Chris Isaak", year: 0, text: "Non ho mai voluto innamorarmi così tanto. Con te non ho potuto farne a meno.", url: "https://www.deezer.com/track/788457" },
  { title: "The Power of Love", artist: "Frankie Goes to Hollywood", year: 0, text: "Ti proteggo io, dai fantasmi e dalle giornate storte. Fidati.", url: "https://www.deezer.com/track/479843892" },
  { title: "Time After Time", artist: "Cyndi Lauper", year: 0, text: "Se ti perdi, guardati indietro: io ci sono. Ogni volta.", url: "https://www.deezer.com/track/72194073" },
  { title: "True Colors", artist: "Cyndi Lauper", year: 0, text: "Mostrami pure i tuoi colori veri: sono la cosa più bella che io conosca.", url: "https://www.deezer.com/track/6067352" },
  { title: "Endless Love", artist: "Diana Ross", year: 0, text: "Sei il mio primo pensiero e l'ultimo. In mezzo, sempre tu.", url: "https://www.deezer.com/track/906584" },
  { title: "I Say a Little Prayer", artist: "Aretha Franklin", year: 0, text: "Prima ancora del caffè, la mattina, penso a te.", url: "https://www.deezer.com/track/2133626" },
  { title: "(You Make Me Feel Like) A Natural Woman", artist: "Aretha Franklin", year: 0, text: "Mi fai sentire semplicemente me stessa. È il regalo più grande.", url: "https://www.deezer.com/track/422942432" },
  { title: "Isn't She Lovely", artist: "Stevie Wonder", year: 0, text: "Ogni volta che ti guardo penso la stessa cosa: ma quanto sei bella.", url: "https://www.deezer.com/track/676011672" },
  { title: "I Just Called to Say I Love You", artist: "Stevie Wonder", year: 0, text: "Nessun motivo particolare. Volevo solo dirti che ti amo.", url: "https://www.deezer.com/track/538709362" },
  { title: "My Cherie Amour", artist: "Stevie Wonder", year: 0, text: "Amore mio, ti guardo da lontano e mi si riempie il petto.", url: "https://www.deezer.com/track/6821052" },
  { title: "Signed, Sealed, Delivered I'm Yours", artist: "Stevie Wonder", year: 0, text: "Firmato, sigillato, consegnato: sono tuo. Da sempre.", url: "https://www.deezer.com/track/788643242" },
  { title: "Lately", artist: "Stevie Wonder", year: 0, text: "Ultimamente penso a te più del solito. Cioè: sempre di più.", url: "https://www.deezer.com/track/538709432" },
  { title: "Crazy", artist: "Patsy Cline", year: 0, text: "Sono pazzo di te, e non ho nessuna voglia di guarire.", url: "https://www.deezer.com/track/542814742" },
  { title: "Dream a Little Dream of Me", artist: "The Mamas & the Papas", year: 0, text: "Stanotte sogna un po' di me: io lo faccio ogni notte con te.", url: "https://www.deezer.com/track/538670442" },
  { title: "Everybody Loves Somebody", artist: "Dean Martin", year: 0, text: "Tutti amano qualcuno, prima o poi. Io ho avuto la fortuna di amare te.", url: "https://www.deezer.com/track/72398167" },
  { title: "The Way You Look Tonight", artist: "Frank Sinatra", year: 0, text: "Un giorno, quando sarò vecchio, ricorderò te esattamente così.", url: "https://www.deezer.com/track/71483062" },
  { title: "I've Got You Under My Skin", artist: "Frank Sinatra", year: 0, text: "Ti porto sottopelle: non c'è verso di toglierti, e non lo voglio.", url: "https://www.deezer.com/track/3105125" },
  { title: "Fly Me to the Moon", artist: "Frank Sinatra", year: 0, text: "Portami dove vuoi tu: basta tenerti la mano.", url: "https://www.deezer.com/track/71483067" },
  { title: "L-O-V-E", artist: "Nat King Cole", year: 0, text: "Quattro lettere per dire una cosa enorme: quello che provo per te.", url: "https://www.deezer.com/track/3158377" },
  { title: "Unforgettable", artist: "Nat King Cole", year: 0, text: "Indimenticabile, ecco cosa sei. In tutti i sensi.", url: "https://www.deezer.com/track/1444376692" },
  { title: "Feeling Good", artist: "Nina Simone", year: 0, text: "È una nuova alba, un nuovo giorno, una nuova vita. E la voglio con te.", url: "https://www.deezer.com/track/709830092" },
  { title: "My Baby Just Cares for Me", artist: "Nina Simone", year: 0, text: "Di tutto il mondo, la cosa che preferisco è che tu tenga a me.", url: "https://www.deezer.com/track/2789439" },
  { title: "Cheek to Cheek", artist: "Ella Fitzgerald", year: 0, text: "Guancia a guancia con te sto in paradiso. Nemmeno mi accorgo del resto.", url: "https://www.deezer.com/track/1942643" },
  { title: "Dream", artist: "Ella Fitzgerald", year: 0, text: "Quando le cose vanno storte, chiudo gli occhi e sogno te.", url: "https://www.deezer.com/track/10218969" },
  { title: "Come Away with Me", artist: "Norah Jones", year: 0, text: "Portami via con te, dove vuoi. Il posto non conta se ci sei.", url: "https://www.deezer.com/track/1064016242" },
  { title: "The Nearness of You", artist: "Norah Jones", year: 0, text: "Non è la luna, non è la musica: è la tua semplice vicinanza a incantarmi.", url: "https://www.deezer.com/track/1751530747" },
  { title: "Lucky", artist: "Jason Mraz", year: 0, text: "Sono fortunato ad amare la mia migliore amica. Sei tu.", url: "https://www.deezer.com/track/845910" },
  { title: "I'm Yours", artist: "Jason Mraz", year: 0, text: "Non c'è molto altro da dire: sono tuo. Fanne quel che vuoi.", url: "https://www.deezer.com/track/2686140" },
  { title: "Better Together", artist: "Jack Johnson", year: 0, text: "Tutto ha più senso quando lo facciamo insieme. Tutto.", url: "https://www.deezer.com/track/2320086" },
  { title: "Banana Pancakes", artist: "Jack Johnson", year: 0, text: "Fingiamo che fuori piova e restiamo a letto: solo io e te.", url: "https://www.deezer.com/track/2320088" },
  { title: "Ho Hey", artist: "The Lumineers", year: 0, text: "Ti appartengo, tu appartieni a me: è la cosa più semplice che io sappia.", url: "https://www.deezer.com/track/757244922" },
  { title: "Death and All His Friends", artist: "Coldplay", year: 0, text: "Alla fine di tutto, se ci sei tu, va bene qualunque cosa.", url: "https://www.deezer.com/track/3160073" },
  { title: "Yellow", artist: "Coldplay", year: 0, text: "Guarderei le stelle tutta la notte, e sarebbero comunque meno luminose di te.", url: "https://www.deezer.com/track/3128096" },
  { title: "Sparks", artist: "Coldplay", year: 0, text: "Ti proteggo io. Anche quando non te ne accorgi, ci sono.", url: "https://www.deezer.com/track/3128095" },
  { title: "Magic", artist: "Coldplay", year: 0, text: "Credo ancora nella magia, sì. La prova sei tu.", url: "https://www.deezer.com/track/75716617" },
  { title: "With or Without You", artist: "U2", year: 0, text: "Con te o senza te non so stare. Per fortuna ho scelto: con te.", url: "https://www.deezer.com/track/912486" },
  { title: "All I Want Is You", artist: "U2", year: 0, text: "Puoi tenerti tutto il resto del mondo. A me basti tu.", url: "https://www.deezer.com/track/2913481731" },
  { title: "Sweetest Thing", artist: "U2", year: 0, text: "Sei la cosa più dolce che mi sia capitata. Senza nemmeno provarci.", url: "https://www.deezer.com/track/347363381" },
  { title: "Chasing Cars", artist: "Snow Patrol", year: 0, text: "Restiamo qui a non fare niente, io e te. Non mi serve altro.", url: "https://www.deezer.com/track/1184425" },
  { title: "Say You Love Me", artist: "Jessie Ware", year: 0, text: "Dimmelo quando ne hai voglia: che mi ami. Io lo penso di continuo.", url: "https://www.deezer.com/track/87397385" },
  { title: "Lost Without You", artist: "Freya Ridings", year: 0, text: "Senza di te mi perdo. Con te trovo perfino le cose che non cercavo.", url: "https://www.deezer.com/track/3481731351" },
  { title: "Skinny Love", artist: "Bon Iver", year: 0, text: "Amiamoci per bene, senza risparmiarci. Ne vale la pena.", url: "https://www.deezer.com/track/73916142" },
  { title: "Holocene", artist: "Bon Iver", year: 0, text: "In mezzo a tutto l'immenso, mi sento piccolo e felice: perché ci sei tu.", url: "https://www.deezer.com/track/75812668" },
  { title: "The Only Exception", artist: "Paramore", year: 0, text: "Non credevo più all'amore. Poi sei arrivata tu, l'unica eccezione.", url: "https://www.deezer.com/track/4288426" },
  { title: "Lover", artist: "Taylor Swift", year: 0, text: "Possiamo lasciare le luci di Natale accese fino a gennaio: questa è casa, con te.", url: "https://www.deezer.com/track/737967302" },
  { title: "Love Story", artist: "Taylor Swift", year: 0, text: "Non importa quanto sia complicata la storia: io scelgo sempre te.", url: "https://www.deezer.com/track/2917264" },
  { title: "Enchanted", artist: "Taylor Swift", year: 0, text: "La cosa più bella di tutta la serata sei stata tu. Lo sei ancora.", url: "https://www.deezer.com/track/2355587775" },
  { title: "You Are the Best Thing", artist: "Ray LaMontagne", year: 0, text: "Di tutte le cose belle che mi sono successe, tu sei la migliore.", url: "https://www.deezer.com/track/477116472" },
  { title: "Hold You in My Arms", artist: "Ray LaMontagne", year: 0, text: "Vieni qui: certi problemi si sciolgono solo tra le braccia giuste.", url: "https://www.deezer.com/track/2863524362" },
  { title: "First Day of My Life", artist: "Bright Eyes", year: 0, text: "Giuro che la mia vita è cominciata il giorno che ti ho incontrata.", url: "https://www.deezer.com/track/1357792772" },
  { title: "Such Great Heights", artist: "The Postal Service", year: 0, text: "Da quassù è tutto perfetto. Deve essere l'effetto che mi fai.", url: "https://www.deezer.com/track/1137149682" },
  { title: "La Cura", artist: "Franco Battiato", year: 0, text: "Ti proteggerò dalle paure delle ipocondrie. Ti porterò soprattutto il silenzio e la pazienza.", url: "https://www.deezer.com/track/2432922" },
  { title: "Caruso", artist: "Lucio Dalla", year: 0, text: "Ti voglio bene assai. Ma tanto tanto bene, sai.", url: "https://www.deezer.com/track/972492" },
  { title: "Attenti al lupo", artist: "Lucio Dalla", year: 0, text: "Una casetta piccola, e dentro tu. Non chiedo altro alla vita.", url: "https://www.deezer.com/track/972494" },
  { title: "Emozioni", artist: "Lucio Battisti", year: 0, text: "Con te ho capito cosa vuol dire seguire un aquilone dentro l'azzurro.", url: "https://www.deezer.com/track/764314592" },
  { title: "I Giardini di Marzo", artist: "Lucio Battisti", year: 0, text: "Il mondo intorno può correre: io mi fermo dove ci sei tu.", url: "https://www.deezer.com/track/764229162" },
  { title: "La canzone del sole", artist: "Lucio Battisti", year: 0, text: "Le bionde trecce, gli occhi azzurri e poi... la cosa più bella resti tu.", url: "https://www.deezer.com/track/764072472" },
  { title: "E penso a te", artist: "Lucio Battisti", year: 0, text: "Faccio mille cose e non ne ricordo una: perché intanto penso a te.", url: "https://www.deezer.com/track/764229182" },
  { title: "Il mio canto libero", artist: "Lucio Battisti", year: 0, text: "In un mondo che non ci vuole più, il nostro amore resta libero.", url: "https://www.deezer.com/track/764304922" },
  { title: "Con te partirò", artist: "Andrea Bocelli", year: 0, text: "Con te partirò per paesi che non ho mai visto. Basta andarci insieme.", url: "https://www.deezer.com/track/136341100" },
  { title: "Vivo per lei", artist: "Andrea Bocelli", year: 0, text: "Vivo per te, e non me ne vergogno per niente.", url: "https://www.deezer.com/track/94107104" },
  { title: "Meraviglioso", artist: "Domenico Modugno", year: 0, text: "Guarda che meraviglia la vita, e quanto di più da quando ci sei tu.", url: "https://www.deezer.com/track/997108" },
  { title: "Nel blu dipinto di blu", artist: "Domenico Modugno", year: 0, text: "Con te volo, e volare così non fa nemmeno paura.", url: "https://www.deezer.com/track/10180259" },
  { title: "La donna cannone", artist: "Francesco De Gregori", year: 0, text: "Ti porterò via con me, oltre il tendone azzurro, fino al cielo.", url: "https://www.deezer.com/track/1082709" },
  { title: "Rimmel", artist: "Francesco De Gregori", year: 0, text: "Certe cose non si dimenticano. Il tuo sguardo, per esempio.", url: "https://www.deezer.com/track/546135" },
  { title: "Buonanotte fiorellino", artist: "Francesco De Gregori", year: 0, text: "Buonanotte, fiorellino: chiudi gli occhi che ci penso io.", url: "https://www.deezer.com/track/546139" },
  { title: "Quattro amici", artist: "Gino Paoli", year: 0, text: "In fondo alla lista delle cose importanti, ci sei sempre tu, prima di tutto.", url: "https://www.deezer.com/track/552339672" },
  { title: "Il cielo in una stanza", artist: "Gino Paoli", year: 0, text: "Quando sei qui con me, questa stanza non ha più pareti: ha il cielo.", url: "https://www.deezer.com/track/1019795" },
  { title: "Sapore di sale", artist: "Gino Paoli", year: 0, text: "Sapore di te sulla pelle: è la mia estate preferita.", url: "https://www.deezer.com/track/73730187" },
  { title: "Senza fine", artist: "Gino Paoli", year: 0, text: "Senza fine, tu trascini la mia vita. E io ti seguo volentieri.", url: "https://www.deezer.com/track/993717" },
  { title: "Che sarà", artist: "José Feliciano", year: 0, text: "Non so cosa sarà di noi domani. So che voglio scoprirlo con te.", url: "https://www.deezer.com/track/1793618567" },
  { title: "La prima cosa bella", artist: "Nicola Di Bari", year: 0, text: "La prima cosa bella che ho avuto dalla vita è il tuo sorriso.", url: "https://www.deezer.com/track/997439" },
  { title: "Anima mia", artist: "Cugini di Campagna", year: 0, text: "Anima mia, torna a casa: qui c'è qualcuno che ti pensa sempre.", url: "https://www.deezer.com/track/129135476" },
  { title: "Ancora", artist: "Eduardo De Crescenzo", year: 0, text: "Ancora, e ancora, e ancora: ti sceglierei mille volte.", url: "https://www.deezer.com/track/1020054" },
  { title: "Almeno tu nell'universo", artist: "Mia Martini", year: 0, text: "In tutto l'universo che cambia, tu resti diversa da tutti. E sei mia.", url: "https://www.deezer.com/track/1696872787" },
  { title: "Minuetto", artist: "Mia Martini", year: 0, text: "Anche quando fa male, con te ne vale la pena. Sempre.", url: "https://www.deezer.com/track/3726883212" },
  { title: "La sera dei miracoli", artist: "Lucio Dalla", year: 0, text: "Con te ogni sera è la sera dei miracoli: basta guardarti.", url: "https://www.deezer.com/track/990408" },
  { title: "Futura", artist: "Lucio Dalla", year: 0, text: "Qualunque cosa ci porti il futuro, lo voglio con te. Solo con te.", url: "https://www.deezer.com/track/990410" },
  { title: "Se telefonando", artist: "Mina", year: 0, text: "Se potessi dirti tutto con una parola, direbbe solo il tuo nome.", url: "https://www.deezer.com/track/523540742" },
  { title: "Grande grande grande", artist: "Mina", year: 0, text: "Sei grande, grande, grande: nei difetti e in tutto il resto. E ti amo così.", url: "https://www.deezer.com/track/9910764" },
  { title: "E se domani", artist: "Mina", year: 0, text: "E se domani, e sottolineo se, dovessi perderti... non ci voglio nemmeno pensare.", url: "https://www.deezer.com/track/523540682" },
  { title: "Parole parole", artist: "Mina", year: 0, text: "A te non servono parole: mi basta lo sguardo per capirti.", url: "https://www.deezer.com/track/9910761" },
  { title: "Ancora ancora ancora", artist: "Mina", year: 0, text: "Ancora un giorno con te e poi un altro, e un altro ancora. Non mi stanco mai.", url: "https://www.deezer.com/track/2505716861" },
  { title: "Vedrai vedrai", artist: "Luigi Tenco", year: 0, text: "Vedrai che un giorno andrà tutto bene. Intanto, ci sei tu, e basta.", url: "https://www.deezer.com/track/1018585" },
  { title: "Mi sono innamorato di te", artist: "Luigi Tenco", year: 0, text: "Mi sono innamorato di te perché non avevo niente da fare. E meno male.", url: "https://www.deezer.com/track/1019382" },
  { title: "Azzurro", artist: "Adriano Celentano", year: 0, text: "Cerco un po' d'Africa in giardino, ma mi basta il tuo profumo per partire lontano.", url: "https://www.deezer.com/track/91547092" },
  { title: "Il tempo se ne va", artist: "Adriano Celentano", year: 0, text: "Il tempo se ne va, ma certe cose no. Come quello che provo per te.", url: "https://www.deezer.com/track/552351072" },
  { title: "Una carezza in un pugno", artist: "Adriano Celentano", year: 0, text: "Con te anche la mia rabbia si scioglie in una carezza.", url: "https://www.deezer.com/track/2407440025" },
  { title: "Ti amo", artist: "Umberto Tozzi", year: 0, text: "Ti amo, e non ho voglia di trovare parole più difficili di così.", url: "https://www.deezer.com/track/1357589612" },
  { title: "Ti sento", artist: "Matia Bazar", year: 0, text: "Ti sento anche a distanza. Sei la mia frequenza preferita.", url: "https://www.deezer.com/track/2479608911" },
  { title: "Vacanze romane", artist: "Matia Bazar", year: 0, text: "Con te ogni giorno feriale sembra una vacanza.", url: "https://www.deezer.com/track/18111575" },
  { title: "Sarà perché ti amo", artist: "Ricchi e Poveri", year: 0, text: "Sarà perché ti amo: che altro vuoi che sia questo tremore?", url: "https://www.deezer.com/track/636405" },
  { title: "Se mi lasci non vale", artist: "Julio Iglesias", year: 0, text: "Se mi lasci non vale, l'abbiamo detto. Quindi resta, per favore.", url: "https://www.deezer.com/track/865252" },
  { title: "La guerra è finita", artist: "Baustelle", year: 0, text: "Con te la guerra è finita davvero. Adesso c'è solo pace.", url: "https://www.deezer.com/track/787203" },
  { title: "Ti regalerò una rosa", artist: "Simone Cristicchi", year: 0, text: "Ti regalerei una rosa e mille cose ancora, se solo sapessi dirtele.", url: "https://www.deezer.com/track/2170433" },
  { title: "Meraviglioso", artist: "Negramaro", year: 0, text: "Che meraviglia sei, e quanto poco te ne accorgi.", url: "https://www.deezer.com/track/1256518402" },
  { title: "Estate", artist: "Negramaro", year: 0, text: "La mia estate migliore ha il tuo nome e non finisce a settembre.", url: "https://www.deezer.com/track/1414986052" },
  { title: "Baciami ancora", artist: "Jovanotti", year: 0, text: "Baciami ancora, che a certe cose non ci si abitua mai.", url: "https://www.deezer.com/track/62439126" },
  { title: "A te", artist: "Jovanotti", year: 0, text: "A te che sei semplicemente la cosa più importante che ho.", url: "https://www.deezer.com/track/922477" },
  { title: "Bella", artist: "Jovanotti", year: 0, text: "Bella, di quella bellezza che non ha bisogno di specchi.", url: "https://www.deezer.com/track/2430686" },
  { title: "Per te", artist: "Jovanotti", year: 0, text: "Ho scritto mille cose, ma la più vera è semplice: per te farei di tutto.", url: "https://www.deezer.com/track/2431267" },
  { title: "L'ombelico del mondo", artist: "Jovanotti", year: 0, text: "Quando ci sei tu, il centro del mondo si sposta esattamente qui.", url: "https://www.deezer.com/track/62439101" },
  { title: "Sere nere", artist: "Tiziano Ferro", year: 0, text: "Anche le sere nere passano, se so che poi ci sei tu.", url: "https://www.deezer.com/track/128561419" },
  { title: "Il regalo più grande", artist: "Tiziano Ferro", year: 0, text: "Voglio farti un regalo: la certezza che ci sarò, sempre.", url: "https://www.deezer.com/track/15665320" },
  { title: "Ti scatterò una foto", artist: "Tiziano Ferro", year: 0, text: "Ti scatterei una foto per fermare esattamente questo istante con te.", url: "https://www.deezer.com/track/90602385" },
  { title: "Rosso relativo", artist: "Tiziano Ferro", year: 0, text: "Da quando ci sei tu, ogni cosa ha un colore in più.", url: "https://www.deezer.com/track/128561315" },
  { title: "Di sole e d'azzurro", artist: "Giorgia", year: 0, text: "Mi hai riempito di sole e d'azzurro una vita che era grigia.", url: "https://www.deezer.com/track/972151" },
  { title: "Gocce di memoria", artist: "Giorgia", year: 0, text: "Ogni goccia di memoria che ho di te la tengo stretta.", url: "https://www.deezer.com/track/15534797" },
  { title: "E poi", artist: "Giorgia", year: 0, text: "E poi ci sei tu, che rendi tutto il resto un dettaglio.", url: "https://www.deezer.com/track/995617" },
  { title: "Come saprei", artist: "Giorgia", year: 0, text: "Come saprei amarti se non ci fossi stata tu a insegnarmelo?", url: "https://www.deezer.com/track/995873" },
  { title: "La prima volta", artist: "Giorgia", year: 0, text: "Ti guardo e mi sembra sempre la prima volta. Ogni giorno.", url: "https://www.deezer.com/track/15655929" },
  { title: "Quando", artist: "Pino Daniele", year: 0, text: "Quando penso alla felicità, penso a un pomeriggio qualunque con te.", url: "https://www.deezer.com/track/1540309172" },
  { title: "Napule è", artist: "Pino Daniele", year: 0, text: "Sei come la mia città: casa, con tutti i suoi rumori. E la amo.", url: "https://www.deezer.com/track/425487342" },
  { title: "Anna verrà", artist: "Pino Daniele", year: 0, text: "Verrai, lo so. E io sarò qui ad aspettarti, come sempre.", url: "https://www.deezer.com/track/425487022" },
  { title: "Ricordati di me", artist: "Antonello Venditti", year: 0, text: "Ricordati di me nei giorni belli. Nei brutti, ci penso io a ricordartelo.", url: "https://www.deezer.com/track/61644252" },
  { title: "Notte prima degli esami", artist: "Antonello Venditti", year: 0, text: "La notte prima di tutto, la cosa che mi calma sei tu.", url: "https://www.deezer.com/track/2847383" },
  { title: "Margherita", artist: "Riccardo Cocciante", year: 0, text: "E scriverò sui muri e per le strade il tuo nome, Margherita mia.", url: "https://www.deezer.com/track/996174" },
  { title: "Bella senz'anima", artist: "Riccardo Cocciante", year: 0, text: "Anche quando litighiamo, alla fine resti la cosa più bella che ho.", url: "https://www.deezer.com/track/985852" },
  { title: "Se stiamo insieme", artist: "Riccardo Cocciante", year: 0, text: "Se stiamo insieme ci sarà un perché. Il mio perché sei tu.", url: "https://www.deezer.com/track/16222662" },
  { title: "Cosa resterà degli anni '80", artist: "Raf", year: 0, text: "Passeranno gli anni e le mode, ma tu resterai la mia cosa preferita.", url: "https://www.deezer.com/track/1343254032" },
  { title: "Il battito animale", artist: "Raf", year: 0, text: "Il mio cuore batte più forte quando ci sei. È così, punto.", url: "https://www.deezer.com/track/1343237732" },
  { title: "Self Control", artist: "Raf", year: 0, text: "Con te perdo ogni controllo, e per una volta va benissimo così.", url: "https://www.deezer.com/track/1345872662" },
  { title: "Sei nell'anima", artist: "Gianna Nannini", year: 0, text: "Sei nell'anima, e lì rimani. Non ti sposta più nessuno.", url: "https://www.deezer.com/track/4016810241" },
  { title: "Meravigliosa creatura", artist: "Gianna Nannini", year: 0, text: "Meravigliosa creatura, sei sola al mondo per me.", url: "https://www.deezer.com/track/4016806861" },
  { title: "Bello e impossibile", artist: "Gianna Nannini", year: 0, text: "Sembrava impossibile, e invece eccoci qui. Meno male.", url: "https://www.deezer.com/track/4016801171" },
  { title: "Notti magiche", artist: "Gianna Nannini", year: 0, text: "Con te ogni notte è magica, anche senza motivo.", url: "https://www.deezer.com/track/1035795002" },
  { title: "Dedicato", artist: "Loredana Bertè", year: 0, text: "Questa, come tante altre cose, è dedicata solo a te.", url: "https://www.deezer.com/track/3920585" },
  { title: "E la luna bussò", artist: "Loredana Bertè", year: 0, text: "Quando tutto tace, resta il tuo respiro accanto. E mi basta.", url: "https://www.deezer.com/track/689370" },
  { title: "Cosa vuoi che sia", artist: "Ligabue", year: 0, text: "Cosa vuoi che sia una vita intera, se posso passarla con te.", url: "https://www.deezer.com/track/6628306" },
  { title: "Certe notti", artist: "Ligabue", year: 0, text: "Certe notti la strada non conta: conta con chi la fai. E io la faccio con te.", url: "https://www.deezer.com/track/6633023" },
  { title: "Ho messo via", artist: "Ligabue", year: 0, text: "Ho messo via un po' di cose, ma te no. Te ti tengo stretta.", url: "https://www.deezer.com/track/6628542" },
  { title: "Piccola stella senza cielo", artist: "Ligabue", year: 0, text: "Piccola stella, un cielo te lo do io. Basta che resti a brillare.", url: "https://www.deezer.com/track/6638609" },
  { title: "Hai un momento Dio?", artist: "Ligabue", year: 0, text: "Se avessi un momento chiederei una cosa sola: che tu resti.", url: "https://www.deezer.com/track/6633021" },
  { title: "Questa è la mia vita", artist: "Ligabue", year: 0, text: "Questa è la mia vita, e la parte migliore sei tu.", url: "https://www.deezer.com/track/6628175" },
  { title: "Ci vuole un fisico bestiale", artist: "Luca Carboni", year: 0, text: "Per amare come amo te ci vuole un cuore bestiale. E ce l'ho.", url: "https://www.deezer.com/track/71128681" },
  { title: "Mare mare", artist: "Luca Carboni", year: 0, text: "Mare mare, vorrei portarti dove l'orizzonte è largo come questo bene.", url: "https://www.deezer.com/track/71128686" },
  { title: "Quello che le donne non dicono", artist: "Fiorella Mannoia", year: 0, text: "So ascoltare anche quello che non dici. È lì che ti amo di più.", url: "https://www.deezer.com/track/1021854" },
  { title: "Il cielo d'Irlanda", artist: "Fiorella Mannoia", year: 0, text: "Ti porterei sotto un cielo grande come questo sentimento.", url: "https://www.deezer.com/track/67267869" },
  { title: "Come si cambia", artist: "Fiorella Mannoia", year: 0, text: "Cambiamo tutti, per amore. Io sono cambiato in meglio, grazie a te.", url: "https://www.deezer.com/track/67267868" },
  { title: "Sally", artist: "Vasco Rossi", year: 0, text: "La vita è un brivido che vola via, ma con te vola più piano e più bello.", url: "https://www.deezer.com/track/135876572" },
  { title: "Albachiara", artist: "Vasco Rossi", year: 0, text: "Respiri piano per non far rumore, e intanto mi riempi tutta la giornata.", url: "https://www.deezer.com/track/418521572" },
  { title: "Un senso", artist: "Vasco Rossi", year: 0, text: "Anche se questa vita un senso non ce l'ha, con te ce l'ha eccome.", url: "https://www.deezer.com/track/135876550" },
  { title: "Vivere", artist: "Vasco Rossi", year: 0, text: "Vivere, anche se sei morto dentro: con te ho ricominciato a farlo.", url: "https://www.deezer.com/track/135876582" },
  { title: "Ti prendo e ti porto via", artist: "Vasco Rossi", year: 0, text: "Ti prendo e ti porto via, lontano dalle giornate storte. Andiamo?", url: "https://www.deezer.com/track/135876556" },
  { title: "Stupendo", artist: "Vasco Rossi", year: 0, text: "È stupendo, questo momento con te. Non svegliarmi, se sto sognando.", url: "https://www.deezer.com/track/135876578" },
  { title: "Gli anni", artist: "Max Pezzali", year: 0, text: "Gli anni passano, ma certe cose no. Come la voglia di stare con te.", url: "https://www.deezer.com/track/67860539" },
  { title: "Sei un mito", artist: "Max Pezzali", year: 0, text: "Per me sei un mito, di quelli veri. E ho la fortuna di conoscerti.", url: "https://www.deezer.com/track/67860541" },
  { title: "La dura legge del gol", artist: "Max Pezzali", year: 0, text: "Nella vita si vince e si perde, ma con te mi sento sempre in vantaggio.", url: "https://www.deezer.com/track/4116294" },
  { title: "Nord sud ovest est", artist: "Max Pezzali", year: 0, text: "Da qualunque parte tu vada, io ti seguo. Sono i miei quattro punti cardinali.", url: "https://www.deezer.com/track/464129902" },
  { title: "Con un deca", artist: "Max Pezzali", year: 0, text: "Non servono grandi cose: bastano una serata e tu, e sono a posto.", url: "https://www.deezer.com/track/62439207" },
  { title: "Tutto molto interessante", artist: "Fabio Rovazzi", year: 0, text: "Di tutto il caos del mondo, l'unica cosa che mi interessa davvero sei tu.", url: "https://www.deezer.com/track/137200898" },
  { title: "L'amore esiste", artist: "Francesca Michielin", year: 0, text: "L'amore esiste, e non è un'idea: ha la tua faccia.", url: "https://www.deezer.com/track/119435308" },
  { title: "Nessun grado di separazione", artist: "Francesca Michielin", year: 0, text: "Tra me e te non c'è nessun grado di separazione. Nemmeno uno.", url: "https://www.deezer.com/track/118975572" },
  { title: "Vorrei ma non posto", artist: "J-Ax e Fedez", year: 0, text: "Vorrei postare quanto ti amo, ma certe cose le tengo solo per noi.", url: "https://www.deezer.com/track/124186476" },
  { title: "Bellissima", artist: "Annalisa", year: 0, text: "Bellissima, e non solo di faccia. Dentro, soprattutto.", url: "https://www.deezer.com/track/1877068787" },
  { title: "Mon Amour", artist: "Annalisa", year: 0, text: "Amore mio, di tutte le lingue del mondo, la mia preferita è il tuo nome.", url: "https://www.deezer.com/track/2202743547" },
  { title: "Brividi", artist: "Mahmood e Blanco", year: 0, text: "Mi vengono i brividi ogni volta. Anche dopo tutto questo tempo.", url: "https://www.deezer.com/track/1641875012" },
  { title: "Soldi", artist: "Mahmood", year: 0, text: "Non servono i soldi per essere ricchi. A me basti tu.", url: "https://www.deezer.com/track/634476092" },
  { title: "Notti in bianco", artist: "Blanco", year: 0, text: "Passerei mille notti in bianco solo per guardarti dormire.", url: "https://www.deezer.com/track/1026600682" },
  { title: "Chiquitita", artist: "ABBA", year: 0, text: "Raccontami cosa non va: le tue spalle non le porti mai da sola.", url: "https://www.deezer.com/track/76376876" },
  { title: "The Winner Takes It All", artist: "ABBA", year: 0, text: "Non voglio vincere niente contro di te. Voglio solo restarci accanto.", url: "https://www.deezer.com/track/884035" },
  { title: "I Have a Dream", artist: "ABBA", year: 0, text: "Ho un sogno, ed è semplice: una vita normale, con te dentro.", url: "https://www.deezer.com/track/884034" },
  { title: "Take a Chance on Me", artist: "ABBA", year: 0, text: "Scommetti su di me: non te ne pentirai. Io su di te l'ho già fatto.", url: "https://www.deezer.com/track/884028" },
  { title: "Dancing Queen", artist: "ABBA", year: 0, text: "Balla come quando avevi diciassette anni: ti guardo e mi innamoro daccapo.", url: "https://www.deezer.com/track/884025" },
  { title: "Words", artist: "Bee Gees", year: 0, text: "Le parole mi mancano sempre, con te. Ma questo lo so dire: ti amo.", url: "https://www.deezer.com/track/538439252" },
  { title: "How Deep Is Your Love", artist: "Bee Gees", year: 0, text: "Quanto è profondo questo bene? Non ho ancora trovato il fondo.", url: "https://www.deezer.com/track/350027751" },
  { title: "To Love Somebody", artist: "Bee Gees", year: 0, text: "Non sai cosa vuol dire amare qualcuno... finché non tocca a te. Io lo so: sei tu.", url: "https://www.deezer.com/track/350027641" },
  { title: "More Than a Woman", artist: "Bee Gees", year: 0, text: "Sei più di tante cose messe insieme. Sei tutto, per come la vedo io.", url: "https://www.deezer.com/track/427219192" },
  { title: "Can't Take My Eyes Off You", artist: "Frankie Valli", year: 0, text: "Non riesco a staccarti gli occhi di dosso. E non ci provo nemmeno.", url: "https://www.deezer.com/track/725689" },
  { title: "My Eyes Adored You", artist: "Frankie Valli", year: 0, text: "Ti ho adorata da lontano prima ancora di sfiorarti la mano.", url: "https://www.deezer.com/track/725695" },
  { title: "Just My Imagination", artist: "The Temptations", year: 0, text: "Non è immaginazione: sei reale, sei qui, e sei mia. Che fortuna.", url: "https://www.deezer.com/track/2499099" },
  { title: "I'll Be There", artist: "The Jackson 5", year: 0, text: "Ovunque tu vada, ci sarò. Basta chiamare, e io arrivo.", url: "https://www.deezer.com/track/4188290" },
  { title: "I Want You Back", artist: "The Jackson 5", year: 0, text: "Se mai dovessi andare, ti verrei a riprendere. Ma resta, che è più semplice.", url: "https://www.deezer.com/track/4188287" },
  { title: "You Are the Sunshine of My Life", artist: "Stevie Wonder", year: 0, text: "Sei il sole della mia vita: per questo ti tengo sempre vicino.", url: "https://www.deezer.com/track/596034712" },
  { title: "Ribbon in the Sky", artist: "Stevie Wonder", year: 0, text: "C'è un filo che ci lega, sottile e resistente. Non si spezza.", url: "https://www.deezer.com/track/538693822" },
  { title: "Overjoyed", artist: "Stevie Wonder", year: 0, text: "Ti ho aspettata, e ne è valsa la pena. Ora traboccante di gioia.", url: "https://www.deezer.com/track/538709422" },
  { title: "Ain't Nobody", artist: "Chaka Khan", year: 0, text: "Nessuno mi fa stare come mi fai stare tu. Nessuno, davvero.", url: "https://www.deezer.com/track/776220" },
  { title: "Sweet Love", artist: "Anita Baker", year: 0, text: "Un amore dolce, tranquillo, senza fretta: quello che ho con te.", url: "https://www.deezer.com/track/717534" },
  { title: "Caught Up in the Rapture", artist: "Anita Baker", year: 0, text: "Perso in te, e non ho nessuna intenzione di ritrovarmi.", url: "https://www.deezer.com/track/3607750" },
  { title: "Distant Lover", artist: "Marvin Gaye", year: 0, text: "Anche quando sei lontana, ti sento addosso. Torna presto.", url: "https://www.deezer.com/track/2432831" },
  { title: "Let's Get It On", artist: "Marvin Gaye", year: 0, text: "Non serve fingere niente con te. Solo stare qui, io e te, adesso.", url: "https://www.deezer.com/track/906616" },
  { title: "How Sweet It Is", artist: "Marvin Gaye", year: 0, text: "Che dolce è essere amati da te. Non lo do per scontato un solo giorno.", url: "https://www.deezer.com/track/541594842" },
  { title: "My Funny Valentine", artist: "Chet Baker", year: 0, text: "Con tutti i tuoi difetti buffi, non cambiare mai. Ti amo così.", url: "https://www.deezer.com/track/3147914" },
  { title: "I Fall in Love Too Easily", artist: "Chet Baker", year: 0, text: "Mi innamoro troppo in fretta, dicono. Di te non me ne pento affatto.", url: "https://www.deezer.com/track/3105857" },
  { title: "Time After Time", artist: "Chet Baker", year: 0, text: "Ogni volta, e poi ancora: ti sceglierei sempre daccapo.", url: "https://www.deezer.com/track/3363457" },
  { title: "Moon River", artist: "Audrey Hepburn", year: 0, text: "Due vagabondi in giro per il mondo: basta che il mondo lo giri con me.", url: "https://www.deezer.com/track/3141854111" },
  { title: "La Bohème", artist: "Charles Aznavour", year: 0, text: "Eravamo giovani e felici, e non lo sapevamo. Con te lo so, adesso.", url: "https://www.deezer.com/track/3413187" },
  { title: "She", artist: "Charles Aznavour", year: 0, text: "Lei è tutto e il contrario di tutto, e io la amo in ogni sua versione.", url: "https://www.deezer.com/track/823257072" },
  { title: "Ne me quitte pas", artist: "Jacques Brel", year: 0, text: "Non lasciarmi. Te lo chiedo piano, ma lo penso forte.", url: "https://www.deezer.com/track/2296855" },
  { title: "La Mer", artist: "Charles Trenet", year: 0, text: "Come il mare, tu: cambi mille volte e resti sempre casa.", url: "https://www.deezer.com/track/3123626" },
  { title: "Les Champs-Élysées", artist: "Joe Dassin", year: 0, text: "In qualsiasi strada, a qualsiasi ora, se ci sei tu è la mia preferita.", url: "https://www.deezer.com/track/561685" },
  { title: "Et si tu n'existais pas", artist: "Joe Dassin", year: 0, text: "E se tu non esistessi, dimmi tu per chi vivrei. Meglio non saperlo.", url: "https://www.deezer.com/track/561686" },
  { title: "La vie en rose", artist: "Édith Piaf", year: 0, text: "Quando mi stringi, vedo la vita in rosa. E non voglio altri colori.", url: "https://www.deezer.com/track/73693857" },
  { title: "Hymne à l'amour", artist: "Édith Piaf", year: 0, text: "Per te farei cose enormi. Per fortuna a te basta che io resti.", url: "https://www.deezer.com/track/29190691" },
  { title: "Perhaps, Perhaps, Perhaps", artist: "Doris Day", year: 0, text: "Basta con i forse: io lo so già. Sei tu, senza dubbi.", url: "https://www.deezer.com/track/2483148" },
  { title: "Dream a Little Dream", artist: "Doris Day", year: 0, text: "Sogna un po' di me stanotte. Io lo faccio ogni notte con te.", url: "https://www.deezer.com/track/2483163" },
  { title: "Sea of Love", artist: "Cat Power", year: 0, text: "Vieni con me in questo mare d'amore: non ti lascio la mano, promesso.", url: "https://www.deezer.com/track/105281106" },
  { title: "The Greatest", artist: "Cat Power", year: 0, text: "Volevo essere il più grande. Poi ho capito: mi bastava essere il tuo.", url: "https://www.deezer.com/track/945521" },
  { title: "Over the Rainbow", artist: "Israel Kamakawiwo'ole", year: 0, text: "Da qualche parte oltre l'arcobaleno c'è un posto per noi. Andiamoci.", url: "https://www.deezer.com/track/418130622" },
  { title: "Lucky Man", artist: "The Verve", year: 0, text: "Mi sento un uomo fortunato. E il motivo, guarda caso, sei tu.", url: "https://www.deezer.com/track/3137509" },
  { title: "Bittersweet Symphony", artist: "The Verve", year: 0, text: "La vita è una sinfonia agrodolce, e con te la parte dolce vince.", url: "https://www.deezer.com/track/3516883161" },
  { title: "Sweet Disposition", artist: "The Temper Trap", year: 0, text: "Momenti rubati, corse a perdifiato: io li voglio tutti con te.", url: "https://www.deezer.com/track/3344814521" },
  { title: "Cherry Wine", artist: "Hozier", year: 0, text: "Ti amo di quell'amore paziente che aspetta, e resta, e non se ne va.", url: "https://www.deezer.com/track/84791759" },
  { title: "Like Real People Do", artist: "Hozier", year: 0, text: "Non chiedo il tuo passato: mi basta il presente, se lo tieni con me.", url: "https://www.deezer.com/track/84791753" },
  { title: "Make You Feel My Love", artist: "Bob Dylan", year: 0, text: "Non c'è niente che non farei per farti sentire quanto sei amata.", url: "https://www.deezer.com/track/2118264907" },
  { title: "I Want You", artist: "Bob Dylan", year: 0, text: "Ti voglio, semplicemente. Senza clausole, senza forse.", url: "https://www.deezer.com/track/15192225" },
  { title: "Home", artist: "Edward Sharpe & The Magnetic Zeros", year: 0, text: "Casa è ovunque io sia con te. Non serve altro indirizzo.", url: "https://www.deezer.com/track/29093801" },
  { title: "First Time Ever I Saw Your Face", artist: "Roberta Flack", year: 0, text: "La prima volta che ho visto il tuo viso, ho pensato: eccola, è lei.", url: "https://www.deezer.com/track/14615239" },
  { title: "Killing Me Softly", artist: "Roberta Flack", year: 0, text: "Mi disarmi con dolcezza, ogni volta. E io mi arrendo felice.", url: "https://www.deezer.com/track/14615242" },
  { title: "Ain't No Sunshine", artist: "Bill Withers", year: 0, text: "Non c'è sole quando non ci sei. E le giornate sono troppo lunghe.", url: "https://www.deezer.com/track/2312047" },
  { title: "Lovely Day", artist: "Bill Withers", year: 0, text: "Basta uno sguardo tuo la mattina e so già che sarà una bella giornata.", url: "https://www.deezer.com/track/70016835" },
  { title: "Just the Two of Us", artist: "Bill Withers", year: 0, text: "Solo io e te, e il cielo sopra. Non mi serve una folla.", url: "https://www.deezer.com/track/3085246" },
  { title: "Lean on Me", artist: "Bill Withers", year: 0, text: "Appoggiati a me quando sei stanca: è per questo che ci sono.", url: "https://www.deezer.com/track/863911" },
  { title: "This Guy's in Love with You", artist: "Herb Alpert", year: 0, text: "Ti guardo e spero che tu lo sappia: questo qui è pazzo di te.", url: "https://www.deezer.com/track/1064003312" },
  { title: "Close to You", artist: "The Carpenters", year: 0, text: "Perché mi voglio stare accanto a te? Perché sei semplicemente tu.", url: "https://www.deezer.com/track/1313843" },
  { title: "We've Only Just Begun", artist: "The Carpenters", year: 0, text: "Abbiamo appena cominciato, tu ed io. E ho voglia di tutto il resto.", url: "https://www.deezer.com/track/529915791" },
  { title: "Top of the World", artist: "The Carpenters", year: 0, text: "Con te sono in cima al mondo, e la vista è meravigliosa.", url: "https://www.deezer.com/track/2876051602" },
  { title: "Rainy Days and Mondays", artist: "The Carpenters", year: 0, text: "Anche i lunedì di pioggia diventano sopportabili, se ci sei tu.", url: "https://www.deezer.com/track/2876051562" },
  { title: "Your Love", artist: "The Outfield", year: 0, text: "Non voglio perdere il tuo amore stanotte. Né nessun'altra notte.", url: "https://www.deezer.com/track/856124" },
  { title: "Africa", artist: "Toto", year: 0, text: "Farei cose insensate pur di restarti vicino. Anche piovesse per sempre.", url: "https://www.deezer.com/track/1079668" },
  { title: "I Won't Give Up", artist: "Jason Mraz", year: 0, text: "Non mollo. Anche quando è dura, io su di noi non mollo.", url: "https://www.deezer.com/track/17827563" },
  { title: "Halo", artist: "Beyoncé", year: 0, text: "Vedo il tuo alone ovunque tu vada. Sei la mia luce, letteralmente.", url: "https://www.deezer.com/track/2553265" },
  { title: "XO", artist: "Beyoncé", year: 0, text: "Nel buio, tu sei la luce che tengo accesa. Sempre.", url: "https://www.deezer.com/track/73724284" },
  { title: "Adorn", artist: "Miguel", year: 0, text: "Lascia che il mio amore ti avvolga. È tutto quello che so fare bene.", url: "https://www.deezer.com/track/51867991" },
  { title: "Best Part", artist: "Daniel Caesar", year: 0, text: "Sei la parte migliore della mia giornata. Ogni giornata.", url: "https://www.deezer.com/track/417767192" },
  { title: "Location", artist: "Khalid", year: 0, text: "Dimmi solo dove sei: il resto della strada la trovo io.", url: "https://www.deezer.com/track/130855506" },
  { title: "Lost in Japan", artist: "Shawn Mendes", year: 0, text: "Attraverserei mezzo mondo solo per passare una sera con te.", url: "https://www.deezer.com/track/504135682" },
  { title: "Say You Won't Let Go", artist: "James Arthur", year: 0, text: "Promettimi che non lasci andare. Io ho già smesso di volerlo.", url: "https://www.deezer.com/track/131742260" },
  { title: "Thinking Out Loud", artist: "Ed Sheeran", year: 0, text: "Ti amerò anche a settant'anni, con la memoria che se ne va. Il tuo nome no.", url: "https://www.deezer.com/track/79875064" },
  { title: "Perfect", artist: "Ed Sheeran", year: 0, text: "Ho trovato una donna più forte di chiunque conosca. E balla con me al buio.", url: "https://www.deezer.com/track/142986206" },
  { title: "Photograph", artist: "Ed Sheeran", year: 0, text: "Ti tengo in una foto, dentro una tasca, vicino al cuore. Dove stai bene.", url: "https://www.deezer.com/track/79875054" },
  { title: "Kiss Me", artist: "Sixpence None the Richer", year: 0, text: "Baciami sotto la luce di mille lampioni: mi sembra sempre la prima volta.", url: "https://www.deezer.com/track/134116940" },
  { title: "Can't Help Falling in Love", artist: "Haley Reinhart", year: 0, text: "Certe cose sagge non si fanno. Innamorarsi di te è la più dolce delle follie.", url: "https://www.deezer.com/track/2590972542" },
  { title: "Falling Like the Stars", artist: "James Arthur", year: 0, text: "Cadiamo insieme, come le stelle. Basta che cadiamo dalla stessa parte.", url: "https://www.deezer.com/track/770299622" },
  { title: "All of Me", artist: "John Legend", year: 0, text: "Ti do tutto di me, e prendo tutto di te. Anche le curve difficili.", url: "https://www.deezer.com/track/70079770" },
  { title: "Ordinary People", artist: "John Legend", year: 0, text: "Siamo persone normali, io e te. E non c'è niente di più bello.", url: "https://www.deezer.com/track/120742460" },
  { title: "Stay with Me", artist: "Sam Smith", year: 0, text: "Resta con me stanotte. E domani, e tutte le notti dopo, se ti va.", url: "https://www.deezer.com/track/111780376" },
  { title: "Latch", artist: "Sam Smith", year: 0, text: "Mi sono aggrappato a te, e non ho nessuna voglia di mollare.", url: "https://www.deezer.com/track/75526535" },
  { title: "Like I'm Gonna Lose You", artist: "Meghan Trainor", year: 0, text: "Ti amo come se potessi perderti domani. Così non do niente per scontato.", url: "https://www.deezer.com/track/113420718" },
  { title: "Bubbly", artist: "Colbie Caillat", year: 0, text: "Mi si accende tutto quando arrivi. Una specie di solletico al cuore.", url: "https://www.deezer.com/track/1087017" },
  { title: "The Way I Am", artist: "Ingrid Michaelson", year: 0, text: "Ti amo per come sei, senza condizioni. Non cambiare un pezzo.", url: "https://www.deezer.com/track/946494132" },
  { title: "Come On Get Higher", artist: "Matt Nathanson", year: 0, text: "Ti sento nelle ossa, come una canzone che non smetto di canticchiare.", url: "https://www.deezer.com/track/3128478" },
  { title: "Marry Me", artist: "Train", year: 0, text: "Non ho niente di pronto, solo la voglia di svegliarmi accanto a te per sempre.", url: "https://www.deezer.com/track/578072512" },
  { title: "Lucky Now", artist: "Ryan Adams", year: 0, text: "Non so se sono più saggio, ma con te di sicuro sono più felice.", url: "https://www.deezer.com/track/13784342" },
  { title: "Come Pick Me Up", artist: "Ryan Adams", year: 0, text: "Vieni a prendermi quando cado. So che lo fai. Lo fai sempre.", url: "https://www.deezer.com/track/63489512" },
  { title: "Harvest Moon", artist: "Neil Young", year: 0, text: "Voglio ancora ballare con te sotto questa luna. Come la prima volta.", url: "https://www.deezer.com/track/677484" },
  { title: "Only Love Can Break Your Heart", artist: "Neil Young", year: 0, text: "Solo l'amore può ferirti, dicono. Il nostro invece mi guarisce.", url: "https://www.deezer.com/track/3826703" },
  { title: "Into the Mystic", artist: "Van Morrison", year: 0, text: "Navighiamo insieme nel mistero, io e te. Non mi serve la mappa.", url: "https://www.deezer.com/track/527900771" },
  { title: "Crazy Love", artist: "Van Morrison", year: 0, text: "Un amore folle, del tipo che ti tira su nei giorni pesanti.", url: "https://www.deezer.com/track/71433038" },
  { title: "Sweet Thing", artist: "Van Morrison", year: 0, text: "Cosa dolce mia, cammineremo tra i giardini bagnati di pioggia. Insieme.", url: "https://www.deezer.com/track/3664182" },
  { title: "These Arms of Mine", artist: "Otis Redding", year: 0, text: "Queste braccia ti aspettano. Vieni, che qui stai al sicuro.", url: "https://www.deezer.com/track/722589" },
  { title: "That's How Strong My Love Is", artist: "Otis Redding", year: 0, text: "Il mio amore è forte come il sole d'estate: non ti abbandona mai.", url: "https://www.deezer.com/track/722600" },
  { title: "I've Been Loving You Too Long", artist: "Otis Redding", year: 0, text: "Ti amo da troppo tempo per smettere adesso. E non voglio.", url: "https://www.deezer.com/track/86490065" },
  { title: "A Change Is Gonna Come", artist: "Sam Cooke", year: 0, text: "Le cose cambieranno in meglio, lo so. Intanto ho te, ed è già tanto.", url: "https://www.deezer.com/track/9938661" },
  { title: "Cupid", artist: "Sam Cooke", year: 0, text: "Cupido, per una volta hai fatto centro: mi hai fatto incontrare lei.", url: "https://www.deezer.com/track/71190918" },
  { title: "Bring It On Home to Me", artist: "Sam Cooke", year: 0, text: "Torna a casa da me. Ti aspetto con la luce accesa.", url: "https://www.deezer.com/track/71190943" },
  { title: "Natural Woman", artist: "Carole King", year: 0, text: "Mi fai sentire semplicemente me stessa. Nessuno ci era mai riuscito.", url: "https://www.deezer.com/track/119819720" },
  { title: "So Far Away", artist: "Carole King", year: 0, text: "Sei lontana e mi manchi, ma so che torni. È questo che mi tiene su.", url: "https://www.deezer.com/track/119819700" },
];

export const SUPPORT_DEDICATIONS: Dedication[] = [
  { title: "Fix You", artist: "Coldplay", year: 0, text: "Non devi aggiustarti da sola: io ci sono, anche per i pezzi.", url: "https://www.deezer.com/track/3106505" },
  { title: "The Scientist", artist: "Coldplay", year: 0, text: "Smetti di riavvolgere il nastro. Il posto migliore da cui guardare è qui, adesso.", url: "https://www.deezer.com/track/3098840" },
  { title: "Beautiful Day", artist: "U2", year: 0, text: "Anche nelle giornate storte c'è un momento buono. Di solito è piccolo: cercalo.", url: "https://www.deezer.com/track/2162742" },
];

/**
 * Ogni giorno ha la sua dedica: la canzone del giorno pesca sempre dalla
 * pool delle dediche (vedi SongWidget), quindi non serve più distinguere i
 * giorni. La domenica resta comunque un "giorno da dedica" per compatibilità.
 */
export function isDedicationDay(_dateStr: string): boolean {
  return true;
}
